"""AGV lane-graph movement and simulation state orchestration."""

from __future__ import annotations

from collections import Counter

from rware.agv_layouts import AGVLayout
from rware.agv_topology import heading_between
from rware.agv_types import AGVAction, AGVState, DETECT_ONLY, Heading, MoveProposal, Route, turn_left, turn_right
from rware.conflict_detector import ConflictDetector
from rware.interaction_area import InteractionAreaRegistry
from rware.interaction_area_manager import InteractionAreaManager


class AGVMovementSimulator:
    """Minimal AGV simulator constrained to predefined routes and lane graph."""

    def __init__(
        self,
        layout: AGVLayout,
        agvs: list[AGVState] | None = None,
        detect_only: bool = DETECT_ONLY,
    ) -> None:
        """Create a simulator for one AGV layout.

        Args:
            layout: AGVLayout containing graph, routes, and interaction areas.
            agvs: Optional initial AGV states.
            detect_only: If True, conflict risk is logged only. If False, a
                simple priority wait hook can be added without changing callers.

        Returns:
            None.
        """

        self.layout = layout
        self.graph = layout.graph
        self.routes = layout.routes
        self.registry = InteractionAreaRegistry(layout.interaction_areas)
        self.interaction_manager = InteractionAreaManager(self.registry)
        self.conflict_detector = ConflictDetector(self.registry)
        self.detect_only = detect_only
        self.step_count = 0
        self.agvs = agvs if agvs is not None else self._default_agvs()
        self.move_log: list[dict] = []
        self.event_log: list[dict] = []
        self.collision_events: list[dict] = []
        self.collision_counters = Counter(
            {
                "node_collision": 0,
                "edge_swap_collision": 0,
                "conflict_point_occupation": 0,
                "conflict_zone_simultaneous_entry": 0,
            }
        )
        for agv in self.agvs:
            self._sync_route_index(agv)
            self._record_events(self.interaction_manager.update_agv_state(agv, self.step_count))

    def _default_agvs(self) -> list[AGVState]:
        assignments = {
            "AGV_1": ("NORTH_TO_SOUTH", 3),
            "AGV_2": ("WEST_TO_EAST", 5),
            "AGV_3": ("EAST_TO_SOUTH", 2),
            "AGV_4": ("SOUTH_TO_NORTH", 1),
        }
        agvs = []
        for robot_id, start_node in self.layout.initial_nodes.items():
            route_id, priority = assignments.get(robot_id, (None, 1))
            if route_id not in self.layout.routes:
                route_id = None
            agvs.append(
                AGVState(
                    robot_id=robot_id,
                    current_node=start_node,
                    previous_node=None,
                    next_node=None,
                    heading=Heading[self.layout.initial_headings[robot_id]],
                    priority=priority,
                    assigned_route_id=route_id,
                )
            )
        return agvs

    def set_route(
        self,
        robot_id: str | int,
        route_id: str,
        node_sequence: list[str],
        route_type: str = "astar",
    ) -> None:
        """Assign a computed route sequence to one AGV.

        Args:
            robot_id: Target robot id.
            route_id: Stable route id to store in the simulator route table.
            node_sequence: Ordered node ids generated by a planner.
            route_type: Route type label.

        Returns:
            None.
        """

        normalized_id = _robot_id(robot_id)
        if not node_sequence:
            raise ValueError(f"Cannot assign empty route to {normalized_id}")
        self.routes[route_id] = Route(
            route_id=route_id,
            entry_direction="AUTO",
            exit_direction="AUTO",
            route_type=route_type,
            node_sequence=list(node_sequence),
            conflict_points_on_route=[
                node_id
                for node_id in node_sequence
                if self.registry.is_conflict_point(node_id)
            ],
        )
        for agv in self.agvs:
            if agv.robot_id == normalized_id:
                agv.assigned_route_id = route_id
                agv.route_index = 0
                if agv.current_node in node_sequence:
                    agv.route_index = node_sequence.index(agv.current_node)
                return
        raise KeyError(f"Unknown AGV id: {normalized_id}")

    def propose_moves(self, actions: dict[str | int, AGVAction | str]) -> dict[str, MoveProposal]:
        """Build movement proposals from requested AGV actions.

        Args:
            actions: Mapping of robot id to AGVAction or action string.

        Returns:
            Dict mapping robot id to MoveProposal.
        """

        normalized_actions = {_robot_id(key): value for key, value in actions.items()}
        proposals = {}
        for agv in self.agvs:
            raw_action = normalized_actions.get(agv.robot_id, AGVAction.WAIT)
            action = raw_action if isinstance(raw_action, AGVAction) else AGVAction(raw_action)
            proposals[agv.robot_id] = self._proposal_for_agv(agv, action)
        return proposals

    def detect_conflicts(self, proposed_moves: dict[str, MoveProposal]) -> list[dict]:
        """Detect conflict risks for the current step.

        Args:
            proposed_moves: Proposed movement data keyed by robot id.

        Returns:
            List of serializable conflict-risk event dictionaries.
        """

        events = self.conflict_detector.detect_conflicts(proposed_moves, self.step_count)
        return [event.to_dict() for event in events]

    def step(self, actions: dict[str | int, AGVAction | str]) -> dict:
        """Advance the AGV simulation by one step.

        Args:
            actions: Mapping from AGV id to forward, turn_left, turn_right, or wait.

        Returns:
            Step debug dictionary with proposals, area events, and conflict events.
        """

        proposals = self.propose_moves(actions)
        conflict_events = self.conflict_detector.detect_conflicts(proposals, self.step_count)
        self._record_conflicts(conflict_events)

        if not self.detect_only:
            proposals = self._apply_simple_priority_wait(proposals, conflict_events)

        area_events = []
        for agv in self.agvs:
            proposal = proposals[agv.robot_id]
            old_node = agv.current_node
            old_heading = agv.heading
            self._apply_proposal(agv, proposal)
            area_events.extend(self.interaction_manager.update_agv_state(agv, self.step_count))
            self.move_log.append(
                {
                    "step": self.step_count,
                    "robot_id": agv.robot_id,
                    "from_node": old_node,
                    "to_node": agv.current_node,
                    "heading_before": old_heading.name,
                    "heading_after": agv.heading.name,
                    "priority": agv.priority,
                    "assigned_route_id": agv.assigned_route_id,
                    "action": proposal.action.value,
                    "valid": proposal.valid,
                    "reason": proposal.reason,
                }
            )

        self._record_events(area_events)
        result = {
            "step": self.step_count,
            "proposals": {robot_id: _proposal_to_dict(proposal) for robot_id, proposal in proposals.items()},
            "interaction_events": [event.to_dict() for event in area_events],
            "conflict_events": [event.to_dict() for event in conflict_events],
        }
        self.step_count += 1
        return result

    def print_layout_summary(self) -> None:
        """Print layout-level debug information."""

        print(f"layout: {self.layout.name}")
        print(f"grid size: {self.layout.grid_size}")
        print(f"node count: {len(self.graph.nodes)}")
        print(f"edge count: {len(self.graph.edges)}")
        print(f"interaction area count: {len(self.layout.interaction_areas)}")
        if self.layout.stations:
            print(f"stations(G): {self.layout.stations}")
        if self.layout.task_nodes:
            print(f"task shelf_access nodes: {self.layout.task_nodes}")
        for area in self.layout.interaction_areas:
            print(f"{area.area_id} ({area.area_type})")
            print(f"  waiting_points: {sorted(area.waiting_points)}")
            print(f"  conflict_points: {sorted(area.conflict_points)}")
            if area.area_id == "IA_CROSS_001":
                print(f"  routes: {sorted(area.allowed_routes)}")

    def print_step_debug(self, step_result: dict) -> None:
        """Print compact per-step debug data.

        Args:
            step_result: Result returned by step().

        Returns:
            None.
        """

        print(f"step: {step_result['step']}")
        for agv in self.agvs:
            print(
                f"  {agv.robot_id}: node={agv.current_node} heading={agv.heading.name} "
                f"priority={agv.priority} route={agv.assigned_route_id} "
                f"mission={agv.mission.phase if agv.mission else None} "
                f"area={agv.current_interaction_area_id} cp={agv.occupied_conflict_point}"
            )
        print(f"  proposals: {step_result['proposals']}")
        print(f"  conflict_events: {step_result['conflict_events']}")

    def print_summary(self) -> None:
        """Compatibility alias for layout summary output."""

        self.print_layout_summary()
        print(f"collision counters: {dict(self.collision_counters)}")

    def debug_snapshot(self) -> dict:
        """Return a serializable debug snapshot for tests and demos."""

        return {
            "layout": self.layout.name,
            "grid_size": self.layout.grid_size,
            "node_count": len(self.graph.nodes),
            "edge_count": len(self.graph.edges),
            "interaction_area_count": len(self.layout.interaction_areas),
            "interaction_areas": self.registry.summary(),
            "agvs": [
                {
                    "robot_id": agv.robot_id,
                    "agv_id": agv.agv_id,
                    "current_node": agv.current_node,
                    "previous_node": agv.previous_node,
                    "next_node": agv.next_node,
                    "heading": agv.heading.name,
                    "priority": agv.priority,
                    "assigned_route_id": agv.assigned_route_id,
                    "mission": {
                        "mission_id": agv.mission.mission_id,
                        "pickup_node": agv.mission.pickup_node,
                        "dropoff_node": agv.mission.dropoff_node,
                        "phase": agv.mission.phase,
                    }
                    if agv.mission
                    else None,
                    "current_interaction_area_id": agv.current_interaction_area_id,
                    "has_entered_communication_zone": agv.has_entered_communication_zone,
                    "is_waiting_at_waiting_point": agv.is_waiting_at_waiting_point,
                    "has_entered_conflict_zone": agv.has_entered_conflict_zone,
                    "occupied_conflict_point": agv.occupied_conflict_point,
                    "waiting_time": agv.waiting_time,
                    "delay_time": agv.delay_time,
                }
                for agv in self.agvs
            ],
            "move_log": list(self.move_log),
            "event_log": list(self.event_log),
            "collision_events": list(self.collision_events),
            "collision_counters": dict(self.collision_counters),
        }

    def _proposal_for_agv(self, agv: AGVState, action: AGVAction) -> MoveProposal:
        if action == AGVAction.WAIT:
            return self._proposal(agv, agv.current_node, action, True, "wait")
        if agv.assigned_route_id and agv.assigned_route_id in self.routes:
            return self._route_proposal(agv, action)

        next_node, _, valid, reason = self.graph.next_for_action(
            agv.current_node,
            agv.heading,
            action,
        )
        return self._proposal(agv, next_node, action, valid, reason)

    def _route_proposal(self, agv: AGVState, action: AGVAction) -> MoveProposal:
        route = self.routes[agv.assigned_route_id]
        self._sync_route_index(agv)
        if agv.route_index >= len(route.node_sequence) - 1:
            return self._proposal(agv, agv.current_node, action, False, "route_completed")

        node = self.graph.nodes[agv.current_node]
        if node.is_blocked:
            return self._proposal(agv, agv.current_node, action, False, "current_node_blocked")
        if action.value not in node.allowed_turns:
            return self._proposal(agv, agv.current_node, action, False, "action_not_allowed_at_node")

        next_node = route.node_sequence[agv.route_index + 1]
        target = self.graph.nodes[next_node]
        if target.is_blocked:
            return self._proposal(agv, agv.current_node, action, False, "target_node_blocked")
        edge_id = f"{agv.current_node}->{next_node}"
        if edge_id not in self.graph.edges:
            return self._proposal(agv, agv.current_node, action, False, "route_edge_missing")

        next_heading = heading_between(node.position, target.position)
        if action == AGVAction.FORWARD and next_heading != agv.heading:
            return self._proposal(agv, agv.current_node, action, False, "turn_required_for_route")
        if action == AGVAction.TURN_LEFT and next_heading != turn_left(agv.heading):
            if action.value in node.allowed_turns:
                return self._proposal(agv, agv.current_node, action, True, "rotate_left_in_place")
            return self._proposal(agv, agv.current_node, action, False, "left_turn_not_on_route")
        if action == AGVAction.TURN_RIGHT and next_heading != turn_right(agv.heading):
            if action.value in node.allowed_turns:
                return self._proposal(agv, agv.current_node, action, True, "rotate_right_in_place")
            return self._proposal(agv, agv.current_node, action, False, "right_turn_not_on_route")
        if action == AGVAction.BACKWARD:
            return self._proposal(agv, agv.current_node, action, False, "backward_disabled")

        return self._proposal(agv, next_node, action, True, "ok")

    def _apply_proposal(self, agv: AGVState, proposal: MoveProposal) -> None:
        old_node = agv.current_node
        agv.next_node = proposal.to_node
        if proposal.valid and proposal.to_node != agv.current_node:
            next_heading = heading_between(
                self.graph.nodes[agv.current_node].position,
                self.graph.nodes[proposal.to_node].position,
            )
            agv.previous_node = agv.current_node
            agv.current_node = proposal.to_node
            agv.heading = next_heading
            agv.waiting_time = 0
            self._sync_route_index(agv)
        elif proposal.valid and proposal.action == AGVAction.TURN_LEFT:
            agv.previous_node = old_node
            agv.heading = turn_left(agv.heading)
            agv.waiting_time = 0
        elif proposal.valid and proposal.action == AGVAction.TURN_RIGHT:
            agv.previous_node = old_node
            agv.heading = turn_right(agv.heading)
            agv.waiting_time = 0
        else:
            agv.previous_node = old_node
            agv.waiting_time += 1
            if not proposal.valid:
                agv.delay_time += 1

    def _sync_route_index(self, agv: AGVState) -> None:
        if not agv.assigned_route_id or agv.assigned_route_id not in self.routes:
            return
        route = self.routes[agv.assigned_route_id]
        if agv.current_node in route.node_sequence:
            agv.route_index = route.node_sequence.index(agv.current_node)

    def _proposal(
        self,
        agv: AGVState,
        to_node: str,
        action: AGVAction,
        valid: bool,
        reason: str,
    ) -> MoveProposal:
        area = self.registry.area_for_node(to_node)
        return MoveProposal(
            robot_id=agv.robot_id,
            from_node=agv.current_node,
            to_node=to_node,
            priority=agv.priority,
            route_id=agv.assigned_route_id,
            action=action,
            valid=valid,
            reason=reason,
            interaction_area_id=area.area_id if area else None,
        )

    def _record_conflicts(self, events) -> None:
        for event in events:
            event_dict = event.to_dict()
            self.collision_events.append(event_dict)
            self.event_log.append(event_dict)
            self.collision_counters[event.event_type] += 1

    def _record_events(self, events) -> None:
        for event in events:
            self.event_log.append(event.to_dict())

    def _apply_simple_priority_wait(self, proposals, conflict_events):
        return proposals


def _robot_id(key: str | int) -> str:
    if isinstance(key, int):
        return f"AGV_{key}"
    if str(key).startswith("AGV_"):
        return str(key)
    if str(key).isdigit():
        return f"AGV_{key}"
    return str(key)


def _proposal_to_dict(proposal: MoveProposal) -> dict:
    return {
        "from_node": proposal.from_node,
        "to_node": proposal.to_node,
        "priority": proposal.priority,
        "route_id": proposal.route_id,
        "action": proposal.action.value,
        "valid": proposal.valid,
        "reason": proposal.reason,
        "interaction_area_id": proposal.interaction_area_id,
    }
